// <auto-generated />
using System;
using CestaFeria.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CestaFeira.Data.Migrations
{
    [DbContext(typeof(ApsContext))]
    [Migration("20241118191627_primeiro")]
    partial class primeiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CestaFeira.Domain.Entityes.PedidoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("IdPedido");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.PedidoProdutoEntity", b =>
                {
                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoProduto", (string)null);
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("imagem")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("valorUnitario")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("IdUsuario");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cel");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Cidade");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Nome");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NomeFantasia");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Perfil");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Senha");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Uf");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpf");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Email", "Senha");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ab52682-7f30-4f2a-abfc-313261d73761"),
                            Ativo = true,
                            Bairro = "Jardim São Carlos",
                            Cel = "(35)11111111",
                            Cidade = "Alfenas",
                            Data = new DateTime(2024, 11, 18, 16, 16, 27, 18, DateTimeKind.Local).AddTicks(9488),
                            Email = "rafael@gmail.com",
                            Nome = "Administrador",
                            NomeFantasia = "",
                            Numero = 555,
                            Perfil = "ADM",
                            Rua = "Juscelino Kubitschek",
                            Senha = "AAAAAAAAAAAAAAAAAAAAAA==.KQQXlYxdzG9eK2531SXUEg==.ehM/BL/Y3GjhPAXNspbr1x3qFiaDZnAR7pWq5sF8t1s=",
                            Uf = "MG",
                            cpf = "13080460812"
                        });
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.PedidoEntity", b =>
                {
                    b.HasOne("CestaFeira.Domain.Entityes.UsuarioEntity", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.PedidoProdutoEntity", b =>
                {
                    b.HasOne("CestaFeira.Domain.Entityes.PedidoEntity", "Pedido")
                        .WithMany("ProdutoPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CestaFeira.Domain.Entityes.ProdutoEntity", "Produto")
                        .WithMany("ProdutoPedidos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.ProdutoEntity", b =>
                {
                    b.HasOne("CestaFeira.Domain.Entityes.UsuarioEntity", "Usuario")
                        .WithMany("Produtos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.PedidoEntity", b =>
                {
                    b.Navigation("ProdutoPedidos");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.ProdutoEntity", b =>
                {
                    b.Navigation("ProdutoPedidos");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.UsuarioEntity", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
